### ISSUE TITLE
Add multi-sensor for an indicator

### ISSUE THREAD

**Issue by Gustra** [Gustra/tiny-dash#16]
It should be possible to connect multiple sensors to the same indicator:
```
- type: Lamp
  sensors:
    - sensor: State  # indicator values are ignored
...
```
There does not need to be any special logic in the indicator. A Lamp would just simply show the last value sent to it. Other indicators, like the #1 MultiMeter would present the value types at the same time.
