### ISSUE TITLE
Add variables to the configuration

### ISSUE THREAD

**Issue by Gustra** [Gustra/tiny-dash#4]
Make it possible to assign- and use variables in the configuration. Possible:

```
- set:
    var1: somevalue
    foo: bar
- set:
    baz: ${var1}-${foo}
```

Idea: perhaps let each value be subject to jinja2 template expansion?
