### ISSUE TITLE
Add configuration loops

### ISSUE THREAD

**Issue by Gustra** [Gustra/tiny-dash#5]
Compare with ansible item loops.

```
- for:
    items:
        - apple
        - orange
    do:
        program: [ 'check-fruit', '{{item}}']
```
